name    'KyleAnderson-btsync'
version '0.0.3'
author 'Kyle Anderson <kyle@xkyle.com'
dependency   'puppetlabs/concat', '1.0.0'
license 'Apache License, Version 2.0'
summary 'Creates folders synchronized by btsync'
description 'Creates folders synchronized by btsync. http://labs.bittorrent.com/experiments/sync.html'
project_page 'https://github.com/solarkennedy/puppet-btsync'
source 'https://github.com/solarkennedy/puppet-btsync'
